### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by JudahGoldstein** [jerry70450/yu-study-buddies#1]
Searching for / adding classes is currently not possible

**Comment by hjjerrychen** [comment]
I'm not sure I understand the issue. Could you elaborate on it further or give an example?

**Comment by hjjerrychen** [comment]
Oh, never mind I see. There is some kind of CORS issue. Thanks for reporting it. I will take a look.

**Comment by hjjerrychen** [comment]
This issue has now been resolved. Thanks @JudahGoldstein for reporting it!
